// AZ-900 학습 데이터: 플래시카드, 퀴즈 문제, 10일 학습 계획 체크리스트
// 모두 정적 데이터이며 별도 빌드 없이 브라우저에서 바로 로드됩니다.
//
// 각 항목은 3단계 설명을 가집니다.
//   - back / explain : 기본 요약 (모든 레벨에 항상 노출)
//   - detail          : 상세 설명 (중급/고급 기본 펼침, 초급은 접힌 상태로 제공)
//   - tip             : 실전 팁·시험 함정 (고급만 기본 펼침, 나머지는 접힌 상태로 제공)

const TOPICS = [
  { key: "cloud-concepts", label: "클라우드 개념", domain: 1 },
  { key: "architecture", label: "Azure 아키텍처", domain: 2 },
  { key: "compute", label: "컴퓨팅 서비스", domain: 2 },
  { key: "networking", label: "네트워킹", domain: 2 },
  { key: "storage", label: "스토리지", domain: 2 },
  { key: "identity-security", label: "ID/보안", domain: 3 },
  { key: "cost-governance", label: "비용 관리·거버넌스", domain: 3 },
  { key: "monitoring-tools", label: "모니터링·관리도구", domain: 3 },
];

const FLASHCARDS = [
  // --- 클라우드 개념 ---
  { topic: "cloud-concepts", front: "고가용성(High Availability)이란?", back: "장애가 발생해도 사전에 합의된 수준으로 서비스가 계속 작동하도록 하는 것. Azure는 SLA로 가용성 수준을 보장.",
    detail: "Azure는 서비스별로 SLA(서비스 수준 계약)를 통해 가용성 목표(예: 99.9%, 99.99%)를 수치로 명시합니다. 가용성을 높이려면 가용성 영역, 가용성 집합, 다중 리전 배포 같은 중복 구성을 함께 사용해야 합니다.",
    tip: "SLA 수치는 시험에 자주 나옵니다. '9가 많을수록' 다운타임 허용치가 줄어든다는 점과, 여러 서비스를 조합하면 복합 SLA(compound SLA)가 달라진다는 점을 기억하세요." },
  { topic: "cloud-concepts", front: "확장성(Scalability)과 탄력성(Elasticity)의 차이는?", back: "확장성: 늘어난 수요를 처리하기 위해 리소스를 추가/제거할 수 있는 능력(수동/자동). 탄력성: 수요 변화에 따라 자동으로 리소스가 늘고 줄어드는 능력.",
    detail: "확장성은 수직 확장(스케일 업: 더 큰 VM으로 교체)과 수평 확장(스케일 아웃: 인스턴스 추가)을 모두 포함하며 수동으로도 가능합니다. 탄력성은 그중에서도 '자동으로' 트래픽에 맞춰 늘고 주는 것에 초점이 있습니다.",
    tip: "시험 문제에서 '자동으로'라는 단어가 있으면 탄력성(Elasticity), 단순히 '늘리거나 줄일 수 있다'는 확장성(Scalability)을 가리키는 경우가 많습니다." },
  { topic: "cloud-concepts", front: "민첩성(Agility)이 클라우드에서 의미하는 것은?", back: "필요한 리소스를 빠르게 만들고 구성해 아이디어를 신속히 제품/서비스로 구현할 수 있는 능력.",
    detail: "민첩성은 새로운 아이디어를 테스트하거나 실패해도 빠르게 되돌릴 수 있는 능력을 포함합니다. 온프레미스라면 하드웨어 구매에 몇 주~몇 달이 걸리지만, 클라우드는 몇 분 안에 리소스를 만들고 없앨 수 있습니다.",
    tip: "'빠른 시장 출시(time to market)'라는 표현이 나오면 민첩성을 가리키는 경우가 많습니다." },
  { topic: "cloud-concepts", front: "CapEx와 OpEx의 차이는?", back: "CapEx(자본 지출): 초기에 대규모 자산을 구매하는 지출. OpEx(운영 지출): 사용한 만큼 지불하는 지출. 클라우드는 CapEx를 OpEx로 전환.",
    detail: "CapEx는 초기에 큰 비용을 지출하고 시간이 지나며 감가상각하는 방식이라 예측이 어렵고 자금이 묶입니다. OpEx는 사용한 만큼만 지불하므로 초기 투자 부담이 없고 필요에 따라 유연하게 조정할 수 있습니다.",
    tip: "'선불로 하드웨어 구매' = CapEx, '사용한 만큼 매달 청구' = OpEx로 연결해서 외우면 헷갈리지 않습니다." },
  { topic: "cloud-concepts", front: "IaaS, PaaS, SaaS의 예시를 각각 하나씩 들면?", back: "IaaS: Azure Virtual Machines. PaaS: Azure App Service. SaaS: Microsoft 365.",
    detail: "IaaS는 서버·네트워크 같은 인프라만 제공해 OS부터 고객이 관리하고, PaaS는 OS와 런타임까지 관리해줘서 코드/데이터에만 집중하면 되며, SaaS는 완성된 애플리케이션을 그대로 사용합니다.",
    tip: "표로 외우면 좋습니다 — IaaS: Virtual Machines, PaaS: App Service/Azure SQL Database, SaaS: Microsoft 365/Dynamics 365." },
  { topic: "cloud-concepts", front: "공유 책임 모델(Shared Responsibility Model)이란?", back: "클라우드 서비스 유형에 따라 보안 책임이 고객과 클라우드 제공자 사이에 분담되는 모델. IaaS로 갈수록 고객 책임이 커지고, SaaS로 갈수록 제공자 책임이 커짐.",
    detail: "물리적 보안, 데이터센터, 호스트 인프라는 IaaS/PaaS/SaaS 모든 경우에 Microsoft가 책임집니다. 반면 데이터 분류, 클라이언트/엔드포인트 보호, 계정·ID 관리는 서비스 모델과 무관하게 항상 고객의 책임입니다.",
    tip: "'항상 고객 책임'인 항목(데이터, 엔드포인트, 계정 관리)과 '항상 Microsoft 책임'인 항목(물리 보안)을 구분해서 외우는 것이 시험에 잘 나옵니다." },
  { topic: "cloud-concepts", front: "퍼블릭 클라우드, 프라이빗 클라우드, 하이브리드 클라우드를 구분하면?", back: "퍼블릭: 제3자가 소유/운영하는 공용 인프라. 프라이빗: 단일 조직 전용 인프라. 하이브리드: 둘을 연결해 함께 사용.",
    detail: "하이브리드 클라우드는 민감한 데이터는 온프레미스(프라이빗)에 두고 확장이 필요한 워크로드는 퍼블릭 클라우드로 보내는 식으로 규정 준수와 유연성을 동시에 얻으려 할 때 사용합니다.",
    tip: "멀티 클라우드(여러 클라우드 공급업체 사용)와 하이브리드 클라우드(온프레미스+클라우드 연결)를 혼동하지 않도록 주의하세요." },
  { topic: "cloud-concepts", front: "종량제(Consumption-based) 모델의 장점은?", back: "사용한 리소스만큼만 비용을 지불하며, 예측 및 필요에 따라 리소스를 유연하게 늘리거나 줄일 수 있음.",
    detail: "종량제는 초기 투자 없이 시작할 수 있고, 사용량 예측이 어려운 신규 서비스나 계절성이 있는 워크로드에 특히 유리합니다. 다만 장기간 예측 가능한 워크로드는 예약 인스턴스 등으로 할인받는 것이 더 경제적일 수 있습니다.",
    tip: "'초기 비용 없음(no upfront cost)'이라는 표현은 종량제 모델의 핵심 특징으로 자주 출제됩니다." },

  // --- Azure 아키텍처 ---
  { topic: "architecture", front: "Azure 리전(Region)이란?", back: "지연 시간을 고려해 정의된 경계 내에 배포된 데이터 센터의 집합. 하나 이상의 데이터 센터로 구성.",
    detail: "하나의 리전 안에는 하나 이상의 데이터센터가 있으며, 리전을 선택할 때는 지연 시간(사용자와의 거리), 데이터 규정 준수(데이터 주권), 제공되는 서비스 목록, 가격을 함께 고려해야 합니다.",
    tip: "모든 Azure 서비스가 모든 리전에서 제공되는 것은 아니라는 점을 기억하세요 — 리전 선택 전 서비스 가용성을 확인해야 합니다." },
  { topic: "architecture", front: "리전 페어(Region Pair)란?", back: "같은 지리적 영역 내 최소 300마일 이상 떨어진 두 리전을 짝지어, 한쪽 리전 장애 시 다른 리전으로 복구를 지원하는 구성.",
    detail: "리전 페어는 같은 지리적 영역(Geography) 안에서 짝을 이루며, Azure의 대규모 업데이트나 재해 발생 시 순차적으로 복구되어 두 리전이 동시에 영향받을 가능성을 낮춥니다.",
    tip: "'재해 복구(DR)'나 '지리적으로 중복 저장'이라는 표현이 나오면 리전 페어 또는 GRS를 떠올리세요." },
  { topic: "architecture", front: "가용성 영역(Availability Zone)이란?", back: "리전 내에서 독립된 전원, 냉각, 네트워크를 갖춘 물리적으로 분리된 데이터센터 그룹(최소 3개). 리전 내 데이터센터 장애로부터 보호.",
    detail: "가용성 영역은 물리적으로 분리되어 있지만 고속·저지연 네트워크로 연결되어 있어, 한 영역에 장애가 발생해도 다른 영역의 워크로드는 계속 작동합니다. 모든 리전이 가용성 영역을 지원하는 것은 아닙니다.",
    tip: "가용성 '영역(Zone)'은 리전 내 여러 물리적 위치, 가용성 '집합(Set)'은 한 데이터센터 내 논리적 그룹 — 이름이 비슷해 헷갈리기 쉬우니 주의하세요." },
  { topic: "architecture", front: "가용성 집합(Availability Set)이란?", back: "동일 데이터센터 내에서 VM을 장애 도메인과 업데이트 도메인에 분산 배치해 하드웨어 장애/유지관리로부터 보호하는 논리적 그룹.",
    detail: "장애 도메인(Fault Domain)은 전원/네트워크를 공유하는 물리적 그룹이고, 업데이트 도메인(Update Domain)은 동시에 재부팅되는 그룹입니다. 가용성 집합은 VM들을 여러 장애/업데이트 도메인에 분산시켜 동시 다운타임을 방지합니다.",
    tip: "가용성 집합은 '같은 데이터센터 안에서의' 보호이고, 가용성 영역은 '데이터센터 자체가 죽어도' 보호한다는 스케일 차이를 기억하세요." },
  { topic: "architecture", front: "Azure 리소스 계층 구조 순서는?", back: "관리 그룹(Management Group) → 구독(Subscription) → 리소스 그룹(Resource Group) → 리소스(Resource).",
    detail: "관리 그룹은 여러 구독에 정책이나 RBAC를 한번에 적용할 때 사용하고, 하위 계층은 상위 계층에 적용된 정책/권한을 상속받습니다. 계층 구조는 최대 6단계의 관리 그룹 깊이까지 지원합니다.",
    tip: "정책과 권한은 '위에서 아래로' 상속된다는 방향을 기억하면 관련 문제를 쉽게 풀 수 있습니다." },
  { topic: "architecture", front: "리소스 그룹(Resource Group)이란?", back: "Azure 솔루션 관련 리소스들을 담는 논리적 컨테이너. 리소스 그룹을 삭제하면 그 안의 모든 리소스가 함께 삭제됨.",
    detail: "리소스 그룹 내 리소스는 서로 다른 리전에 있어도 되지만, 리소스 그룹 자체는 하나의 리전에 메타데이터를 저장합니다. 수명 주기가 비슷한 리소스를 함께 묶는 것이 모범 사례입니다.",
    tip: "'실수로 전체 삭제'를 막고 싶다면 리소스 그룹이 아니라 리소스 잠금(Resource Lock)을 함께 사용해야 한다는 점이 자주 출제됩니다." },
  { topic: "architecture", front: "Azure Resource Manager(ARM)의 역할은?", back: "Azure 리소스를 배포, 관리, 구성하기 위한 배포/관리 계층. 포털, CLI, PowerShell, REST API 요청이 모두 ARM을 거쳐 처리됨.",
    detail: "ARM은 요청을 인증·인가한 뒤 각 리소스 공급자(Resource Provider)에 전달하는 일관된 관리 계층입니다. ARM 템플릿(JSON/Bicep)을 사용하면 인프라를 코드로 선언해 반복 가능하게 배포할 수 있습니다(IaC).",
    tip: "'모든 관리 도구(Portal/CLI/PowerShell/SDK)가 동일한 API를 거친다'는 표현은 ARM을 가리킵니다." },
  { topic: "architecture", front: "소버린 리전(Sovereign Region)이란?", back: "특별한 규정/컴플라이언스 요구(예: 정부기관용) 때문에 일반 Azure 퍼블릭 클라우드와 분리 운영되는 리전. 예: Azure Government, Azure China.",
    detail: "소버린 리전은 일반 Azure 글로벌 네트워크와 물리적으로 분리되어 운영되며, 특정 국가의 엄격한 데이터 주권·컴플라이언스 요구사항(예: 미국 정부 기관, 중국 현지 법규)을 충족하기 위해 존재합니다.",
    tip: "일반 구독으로는 소버린 리전에 접근할 수 없고, 별도의 자격 심사와 전용 구독이 필요하다는 점을 기억하세요." },

  // --- 컴퓨팅 서비스 ---
  { topic: "compute", front: "Azure Virtual Machines는 어떤 서비스 모델?", back: "IaaS(Infrastructure as a Service). OS와 미들웨어까지 고객이 직접 관리.",
    detail: "VM은 가장 유연하지만 OS 패치, 미들웨어 설치, 보안 구성까지 고객이 직접 관리해야 하므로 운영 부담이 가장 큽니다. 레거시 애플리케이션을 그대로 마이그레이션할 때 주로 사용합니다.",
    tip: "'세밀한 제어가 필요하다', 'OS를 직접 다뤄야 한다'는 표현이 나오면 VM(IaaS)을 정답으로 고려하세요." },
  { topic: "compute", front: "VM 확장 집합(Virtual Machine Scale Sets)이란?", back: "동일하게 구성된 VM 집합을 만들고 관리해, 수요에 따라 자동으로 확장/축소(Autoscale)할 수 있게 하는 서비스.",
    detail: "Scale Sets는 Load Balancer/Application Gateway와 함께 사용해 트래픽을 여러 VM 인스턴스에 분산하며, CPU 사용률 같은 지표를 기준으로 인스턴스 수를 자동 조정(Autoscale)할 수 있습니다.",
    tip: "'동일한 VM을 대량으로, 자동으로 확장'이라는 조건이 나오면 VM Scale Sets가 정답입니다." },
  { topic: "compute", front: "Azure App Service는 어떤 서비스 모델?", back: "PaaS. 웹앱, REST API, 모바일 백엔드를 호스팅하며 인프라 관리 없이 코드 배포에 집중 가능.",
    detail: "App Service는 배포 슬롯(Deployment Slot)을 이용한 무중단 배포, 자동 확장, 내장 인증 등을 제공해 웹앱을 빠르게 운영할 수 있게 해줍니다. 여러 언어(.NET, Java, Node.js, Python 등)를 지원합니다.",
    tip: "'인프라 관리 없이 웹앱만 빠르게 배포'라는 조건은 App Service(PaaS)를 가리키는 전형적 표현입니다." },
  { topic: "compute", front: "Azure Container Instances(ACI)의 특징은?", back: "VM 프로비저닝이나 오케스트레이션 없이 컨테이너를 가장 빠르고 간단하게 실행할 수 있는 서버리스 컨테이너 서비스.",
    detail: "ACI는 오케스트레이터(Kubernetes 등) 없이 단일 컨테이너 또는 컨테이너 그룹을 초 단위로 실행할 수 있어, 짧게 실행되는 작업(배치 작업, 빌드 작업)에 적합합니다.",
    tip: "'가장 빠르고 간단하게', '오케스트레이션 불필요'라는 표현은 AKS가 아니라 ACI를 가리킵니다 — 혼동하기 쉬우니 주의하세요." },
  { topic: "compute", front: "Azure Kubernetes Service(AKS)란?", back: "관리형 Kubernetes 클러스터 서비스로, 컨테이너화된 애플리케이션의 배포/확장/운영을 자동화.",
    detail: "AKS는 컨트롤 플레인(마스터 노드) 관리를 Microsoft가 무료로 대신 해주고, 고객은 워커 노드만 관리하면 됩니다. 대규모 마이크로서비스 애플리케이션 운영에 적합합니다.",
    tip: "'컨테이너 오케스트레이션', '자동 복구/롤아웃/스케일링이 필요한 대규모 컨테이너 환경'이라는 표현은 AKS를 가리킵니다." },
  { topic: "compute", front: "Azure Functions의 특징은?", back: "서버리스 컴퓨트 서비스. 이벤트에 반응해 코드를 실행하며, 사용한 실행 시간만큼만 과금(Consumption plan).",
    detail: "Functions는 HTTP 요청, 타이머, 큐 메시지 등 다양한 트리거로 실행되며, Consumption plan에서는 사용하지 않을 때 완전히 스케일 다운(0개 인스턴스)되어 비용이 발생하지 않습니다.",
    tip: "'이벤트 기반', '사용한 만큼만 과금', '서버 관리 불필요'라는 조합은 Azure Functions를 가리키는 전형적 신호입니다." },
  { topic: "compute", front: "Azure Functions와 Logic Apps의 차이는?", back: "Functions: 코드 기반으로 이벤트에 반응해 로직 실행. Logic Apps: 코드 없이(Low-code) 워크플로우를 시각적으로 설계해 여러 서비스를 연결.",
    detail: "Functions는 개발자가 코드로 세밀한 로직을 구현할 때, Logic Apps는 Microsoft 365·Salesforce 등 다양한 커넥터를 코드 없이 연결해 업무 프로세스를 자동화할 때 적합합니다. 둘은 서로 호출하며 함께 쓰이기도 합니다.",
    tip: "'워크플로우를 시각적으로 디자인'이라는 표현은 Logic Apps, '이벤트에 반응하는 코드 실행'은 Functions로 구분하세요." },
  { topic: "compute", front: "Azure Virtual Desktop이란?", back: "클라우드에서 Windows 데스크톱과 앱을 가상화해 어디서든 접속할 수 있게 하는 데스크톱/앱 가상화 서비스(DaaS).",
    detail: "AVD는 여러 사용자가 하나의 Windows 세션 호스트를 공유하는 멀티세션 Windows 10/11을 지원해 라이선스 비용을 절감할 수 있으며, 재택근무·원격근무 환경에서 중앙 관리형 데스크톱을 제공하는 데 사용됩니다.",
    tip: "'가상 데스크톱', '어디서든 동일한 업무 환경 접속'이라는 표현이 나오면 Azure Virtual Desktop을 떠올리세요." },

  // --- 네트워킹 ---
  { topic: "networking", front: "가상 네트워크(Virtual Network, VNet)란?", back: "Azure 리소스들이 서로 및 인터넷, 온프레미스 네트워크와 안전하게 통신하도록 하는 Azure 네트워킹의 기본 구성 요소.",
    detail: "VNet 안에서 서브넷으로 논리적으로 나누어 리소스를 격리·관리할 수 있고, Network Security Group(NSG)으로 서브넷/NIC 단위 트래픽을 필터링합니다. VNet은 리전 단위 리소스입니다.",
    tip: "VNet은 그 자체로 비용이 들지 않으며(무료), 연결된 게이트웨이나 트래픽에만 과금된다는 점이 시험에 나올 수 있습니다." },
  { topic: "networking", front: "VPN Gateway란?", back: "인터넷을 통해 온프레미스 네트워크와 Azure VNet 간, 또는 VNet 간에 암호화된 트래픽을 전송하는 게이트웨이.",
    detail: "VPN Gateway는 IPsec/IKE 프로토콜로 암호화된 터널을 만들며, 사이트 간(Site-to-Site), 지점 대 사이트(Point-to-Site), VNet 간(VNet-to-VNet) 연결을 지원합니다. 인터넷 회선의 대역폭/지연에 영향을 받습니다.",
    tip: "'인터넷을 통한 암호화된 연결'이라는 표현은 VPN Gateway, 'ISP를 통한 전용 회선'은 ExpressRoute로 구분하세요." },
  { topic: "networking", front: "ExpressRoute란?", back: "공용 인터넷을 거치지 않고 전용 사설 연결로 온프레미스와 Azure를 연결하는 서비스. 더 높은 보안성, 안정성, 낮은 지연 시간 제공.",
    detail: "ExpressRoute는 연결 제공업체(파트너)의 인프라를 통해 Azure와 직접 연결되며, 최대 100Gbps까지의 대역폭과 더 높은 안정성·보안·낮은 지연 시간을 제공해 대용량/미션 크리티컬 워크로드에 적합합니다.",
    tip: "ExpressRoute는 트래픽이 공용 인터넷을 거치지 않으므로 SLA가 VPN Gateway보다 높다는 점을 기억하세요." },
  { topic: "networking", front: "VPN Gateway와 ExpressRoute의 핵심 차이는?", back: "VPN Gateway는 인터넷 기반 암호화 터널, ExpressRoute는 통신사를 통한 전용 사설 연결(인터넷 미경유).",
    detail: "비용과 구축 기간 측면에서는 VPN Gateway가 더 빠르고 저렴하게 시작할 수 있고, ExpressRoute는 통신사와의 회선 설치 절차가 필요해 구축 기간이 더 깁니다. 두 방식을 동시에 구성해 ExpressRoute 장애 시 VPN으로 자동 전환(failover)하는 구성도 가능합니다.",
    tip: "'페일오버 구성'을 묻는 문제에서는 ExpressRoute + VPN Gateway 병행 구성이 정답으로 나올 수 있습니다." },
  { topic: "networking", front: "Load Balancer와 Application Gateway의 차이는?", back: "Load Balancer: OSI 4계층(전송 계층)에서 TCP/UDP 트래픽 분산. Application Gateway: 7계층(애플리케이션 계층)에서 URL 기반 라우팅 등 HTTP(S) 트래픽 처리(WAF 포함 가능).",
    detail: "Load Balancer는 프로토콜(TCP/UDP) 수준에서 빠르게 트래픽을 분산하는 반면, Application Gateway는 HTTP(S) 요청의 URL 경로나 호스트 헤더를 보고 라우팅하며 Web Application Firewall(WAF)로 SQL 인젝션 같은 공격을 방어할 수 있습니다.",
    tip: "'웹 애플리케이션 방화벽(WAF)'이라는 단어가 나오면 무조건 Application Gateway(또는 Front Door)를 떠올리세요." },
  { topic: "networking", front: "Azure Traffic Manager란?", back: "DNS 기반으로 여러 리전에 분산된 서비스 엔드포인트에 트래픽을 분산시키는 글로벌 트래픽 라우팅 서비스.",
    detail: "Traffic Manager는 실제 트래픽을 중계하지 않고 DNS 응답만 제어하여 사용자를 가장 적절한 리전의 엔드포인트로 안내합니다. 우선순위, 가중치, 지리적 위치, 성능 등 다양한 라우팅 방법을 지원합니다.",
    tip: "Traffic Manager는 'DNS 기반'이라 리전 수준(글로벌) 라우팅에, Load Balancer는 리전 내부 라우팅에 사용된다는 계층 차이를 기억하세요." },
  { topic: "networking", front: "Azure CDN(Content Delivery Network)이란?", back: "전 세계에 분산된 서버 네트워크를 통해 정적 콘텐츠를 사용자와 가까운 곳에서 제공해 지연 시간을 줄이는 서비스.",
    detail: "CDN은 원본 서버의 콘텐츠를 전 세계 에지 서버(POP)에 캐싱해두어 사용자가 지리적으로 가장 가까운 서버에서 콘텐츠를 받도록 하며, 원본 서버의 부하도 함께 줄여줍니다.",
    tip: "'정적 콘텐츠(이미지, 동영상, JS/CSS)를 전 세계에 빠르게 전달'이라는 표현은 CDN을 가리킵니다." },
  { topic: "networking", front: "Azure DNS의 역할은?", back: "Azure 인프라를 이용해 도메인 이름을 호스팅하고 관리하는 서비스.",
    detail: "Azure DNS는 Azure의 글로벌 네트워크 인프라를 이용해 매우 빠른 응답 속도와 높은 가용성을 제공하며, 사용자 지정 도메인을 Azure 리소스에 매핑하는 데 사용됩니다. 도메인 이름 등록 자체는 제공하지 않습니다.",
    tip: "Azure DNS는 '도메인을 사는 곳'이 아니라 '이미 있는 도메인의 이름을 관리(호스팅)하는 서비스'라는 점에 유의하세요." },

  // --- 스토리지 ---
  { topic: "storage", front: "Azure Blob Storage란?", back: "텍스트, 이미지, 동영상 등 대용량 비정형(unstructured) 데이터를 저장하기 위한 객체 스토리지.",
    detail: "Blob Storage는 블록 Blob(텍스트/바이너리 파일), 추가 Blob(로그처럼 계속 추가되는 데이터), 페이지 Blob(VM 디스크 등 임의 읽기/쓰기)의 세 가지 유형을 지원하는 객체 스토리지입니다.",
    tip: "'대용량 비정형 데이터', '웹사이트 정적 파일 호스팅'이라는 표현은 Blob Storage를 가리킵니다." },
  { topic: "storage", front: "Blob 스토리지의 3가지 액세스 계층(Access tier)은?", back: "Hot(자주 접근), Cool(가끔 접근, 최소 30일 보관), Archive(거의 접근 안 함, 오프라인, 최소 180일 보관).",
    detail: "계층은 언제든 전환할 수 있지만, Cool/Archive에서 자주 데이터를 읽으면 조기 삭제 수수료나 트랜잭션 비용이 늘어날 수 있습니다. Archive 계층의 데이터를 읽으려면 먼저 Hot/Cool로 재수화(rehydrate)해야 하며 시간이 걸립니다.",
    tip: "'즉시 접근 불가, 재수화 필요'라는 표현이 나오면 Archive 계층을 가리킵니다." },
  { topic: "storage", front: "LRS, ZRS, GRS의 차이는?", back: "LRS: 동일 데이터센터 내 3개 복제본. ZRS: 리전 내 여러 가용성 영역에 복제. GRS: 주 리전 + 페어 리전(다른 지역)에 복제.",
    detail: "GRS는 평상시 보조 리전 데이터에 직접 읽기 접근을 할 수 없지만, RA-GRS를 사용하면 보조 리전에서도 읽기가 가능합니다. GZRS는 ZRS(영역 중복)와 GRS(지역 중복)를 결합해 가장 높은 내구성을 제공합니다.",
    tip: "내구성 순서: LRS < ZRS < GRS < GZRS. '리전 전체 재해 대비'는 GRS 이상, 'AZ 장애만 대비'는 ZRS로 충분합니다." },
  { topic: "storage", front: "Azure Disk Storage는 어떤 용도?", back: "Azure VM에 연결하는 블록 수준 스토리지 볼륨(가상 하드 디스크).",
    detail: "Azure Disk Storage는 HDD, SSD(Standard/Premium), Ultra Disk 등 다양한 성능 등급을 제공하며, 하나의 관리 디스크는 한 번에 하나의 VM에만 연결(attach)할 수 있습니다(공유 디스크 기능 제외).",
    tip: "'VM의 OS/데이터 디스크'라는 표현이 나오면 Disk Storage, '여러 VM/사용자가 동시에 접근'이라는 표현은 Azure Files를 가리킵니다." },
  { topic: "storage", front: "Azure Files의 특징은?", back: "SMB/NFS 프로토콜을 지원하는 완전관리형 클라우드 파일 공유. 온프레미스와 클라우드에서 동시에 마운트 가능.",
    detail: "Azure Files는 온프레미스 파일 서버를 완전히 대체하거나(리프트 앤 시프트), Azure File Sync를 이용해 온프레미스 서버와 클라우드 간 파일을 동기화하는 하이브리드 구성에도 사용됩니다.",
    tip: "'여러 VM/사용자가 동시에 같은 파일 공유에 접근'해야 한다는 조건이 나오면 Disk Storage가 아니라 Azure Files가 정답입니다." },
  { topic: "storage", front: "Azure Migrate의 역할은?", back: "온프레미스 서버/VM/데이터베이스를 Azure로 평가하고 마이그레이션하는 것을 지원하는 허브 서비스.",
    detail: "Azure Migrate는 온프레미스 서버의 사용률을 분석해 적절한 Azure VM 크기를 추천하고 예상 비용까지 산출해주는 평가(assessment) 기능과, 실제 마이그레이션을 수행하는 기능을 함께 제공하는 허브입니다.",
    tip: "'마이그레이션 전 사전 평가/사이징'이라는 표현이 나오면 Azure Migrate를 가리킵니다." },
  { topic: "storage", front: "Azure Data Box란?", back: "대용량 오프라인 데이터를 물리적 장치를 이용해 Azure로 전송하는 서비스. 네트워크 대역폭이 부족할 때 사용.",
    detail: "Data Box는 물리적 저장 장치(수십 TB~PB급)를 고객에게 배송해 데이터를 담아 Microsoft로 다시 보내면 Azure에 업로드해주는 서비스로, 네트워크로 전송하면 수 주~수개월이 걸릴 대용량 데이터를 며칠 내에 옮길 수 있습니다.",
    tip: "'네트워크 대역폭이 부족하거나 매우 느릴 때'라는 조건이 나오면 Data Box를 정답으로 고려하세요." },

  // --- ID/보안 ---
  { topic: "identity-security", front: "인증(Authentication)과 인가(Authorization)의 차이는?", back: "인증: 사용자가 누구인지 확인하는 과정. 인가: 인증된 사용자가 무엇에 접근할 수 있는지 권한을 결정하는 과정.",
    detail: "인증은 보통 로그인(아이디/비밀번호, 생체인식 등)으로 이루어지고, 인가는 인증 이후 RBAC 같은 메커니즘으로 '무엇을 할 수 있는지'를 결정합니다. 인증이 실패하면 인가 단계로 넘어가지 않습니다.",
    tip: "영어 단어로 Authentication(누구인가) vs Authorization(무엇을 할 수 있는가)을 명확히 구분해서 외우세요." },
  { topic: "identity-security", front: "Microsoft Entra ID(구 Azure AD)란?", back: "클라우드 기반 ID 및 액세스 관리 서비스로, 사용자가 Microsoft 365, Azure Portal, 기타 SaaS 앱에 로그인/접근할 수 있게 함.",
    detail: "Entra ID는 온프레미스 Active Directory와 다르게 클라우드 네이티브 서비스이며, Azure AD Connect를 통해 온프레미스 AD와 동기화(하이브리드 ID)할 수 있습니다. SSO, MFA, 조건부 액세스 등의 기능을 제공합니다.",
    tip: "Entra ID는 디렉터리 서비스이고 RBAC(권한 부여)는 별개의 기능이라는 점 — 'ID 저장/인증'은 Entra ID, '리소스 권한 부여'는 RBAC로 구분하세요." },
  { topic: "identity-security", front: "다단계 인증(MFA)이란?", back: "비밀번호 외에 추가로 하나 이상의 인증 방법(문자, 앱 알림, 생체인식 등)을 요구해 보안을 강화하는 방식.",
    detail: "MFA는 지식 요소(비밀번호), 소유 요소(휴대폰, 보안 키), 생체 요소(지문, 얼굴 인식) 중 최소 두 가지를 요구합니다. 비밀번호가 유출되어도 추가 인증 요소가 없으면 로그인을 막을 수 있어 계정 탈취 공격을 크게 줄여줍니다.",
    tip: "'비밀번호 유출 방어'와 관련된 시험 문제에는 대부분 MFA가 정답으로 나옵니다." },
  { topic: "identity-security", front: "조건부 액세스(Conditional Access)란?", back: "위치, 기기 상태, 위험도 등 신호(signal)를 바탕으로 액세스 제어 결정을 자동화하는 정책 기반 기능.",
    detail: "조건부 액세스는 'IF-THEN' 정책 형태로 동작합니다 — 예를 들어 '회사 네트워크 밖에서 로그인하면(IF) MFA를 요구한다(THEN)'처럼 신호에 따라 접근을 허용, 차단, 추가 인증 요구로 제어합니다.",
    tip: "조건부 액세스는 Entra ID Premium 라이선스가 필요한 기능이라는 점도 함께 기억해두면 좋습니다." },
  { topic: "identity-security", front: "RBAC(역할 기반 액세스 제어)란?", back: "사용자/그룹에게 리소스에 대한 특정 역할(예: Reader, Contributor, Owner)을 할당해 세분화된 액세스 관리를 제공하는 인가 시스템.",
    detail: "RBAC의 역할은 관리 그룹, 구독, 리소스 그룹, 리소스 중 어느 범위(scope)에도 할당할 수 있으며, 상위 범위에서 부여된 역할은 하위 범위로 상속됩니다. Owner, Contributor, Reader가 가장 기본적인 내장 역할입니다.",
    tip: "Contributor는 리소스를 관리할 수 있지만 '다른 사람에게 권한을 부여'할 수는 없고, 그 권한 위임은 Owner만 가능하다는 차이를 기억하세요." },
  { topic: "identity-security", front: "제로 트러스트(Zero Trust) 원칙 3가지는?", back: "명시적으로 검증(Verify explicitly), 최소 권한 액세스(Least privileged access) 사용, 침해 가정(Assume breach).",
    detail: "전통적인 보안 모델은 '사내망 안쪽은 안전하다'고 가정했지만, 제로 트러스트는 내부/외부를 가리지 않고 모든 요청을 매번 검증합니다. 사용자, 기기, 위치, 데이터 신호를 종합해 접근을 판단합니다.",
    tip: "제로 트러스트의 3원칙(명시적 검증, 최소 권한, 침해 가정)은 영어 원문 그대로 나올 수 있으니 함께 알아두세요." },
  { topic: "identity-security", front: "심층 방어(Defense in depth)란?", back: "물리 보안, ID/액세스, 경계, 네트워크, 컴퓨팅, 애플리케이션, 데이터 등 여러 계층에서 방어를 겹겹이 적용하는 보안 전략.",
    detail: "심층 방어는 하나의 보안 계층이 뚫리더라도 다음 계층이 공격을 막아내도록 설계하는 전략으로, 물리 보안부터 데이터까지 총 7개 계층(물리, ID/액세스, 경계, 네트워크, 컴퓨팅, 애플리케이션, 데이터)으로 설명됩니다.",
    tip: "가장 안쪽 계층이 '데이터'라는 점 — 결국 모든 보안 계층의 목적은 데이터를 보호하는 것이라는 논리로 출제됩니다." },
  { topic: "identity-security", front: "Microsoft Defender for Cloud의 역할은?", back: "하이브리드/멀티클라우드 워크로드에 대한 보안 상태를 강화하고 위협을 탐지/대응하는 통합 보안 관리 도구(CSPM/CWPP).",
    detail: "Defender for Cloud는 무료 계층(보안 점수, 권장사항)과 유료 계층(Defender plans, 실시간 위협 탐지)으로 나뉘며, Azure뿐 아니라 AWS/GCP 및 온프레미스 리소스까지 보안 상태를 통합 관리할 수 있습니다.",
    tip: "'보안 점수(Secure Score)'라는 용어가 나오면 Defender for Cloud를 가리킵니다." },
  { topic: "identity-security", front: "Microsoft Sentinel이란?", back: "클라우드 기반 SIEM(보안 정보 이벤트 관리) + SOAR(보안 오케스트레이션 자동 대응) 솔루션. 조직 전체의 보안 이벤트를 수집/분석.",
    detail: "Sentinel은 여러 소스(방화벽, Entra ID, Microsoft 365 등)의 로그를 수집해 AI/머신러닝으로 위협을 탐지하고, 플레이북(자동화된 대응 워크플로우)으로 자동 대응까지 수행할 수 있는 클라우드 네이티브 솔루션입니다.",
    tip: "'조직 전체의 보안 이벤트를 한 곳에서 수집·분석·대응'이라는 표현은 Sentinel을 가리키며, Defender for Cloud(리소스 보안 상태 관리)와 역할이 다르다는 점에 유의하세요." },

  // --- 비용 관리·거버넌스 ---
  { topic: "cost-governance", front: "Pricing Calculator와 TCO Calculator의 차이는?", back: "Pricing Calculator: Azure 서비스 예상 비용을 사전에 견적. TCO Calculator: 온프레미스 인프라 대비 Azure로 이전 시 총소유비용 절감액을 비교.",
    detail: "Pricing Calculator는 아직 Azure를 쓰지 않아도 원하는 서비스 구성으로 예상 월 비용을 바로 계산할 수 있고, TCO Calculator는 현재 온프레미스 인프라 정보(서버 수, 스토리지 등)를 입력해 Azure 이전 시 절감액을 비교해줍니다.",
    tip: "'이미 온프레미스를 운영 중이며 Azure로 옮기면 얼마나 절감되는지'를 묻는 문제는 TCO Calculator가 정답입니다." },
  { topic: "cost-governance", front: "Azure Cost Management란?", back: "Azure 지출을 모니터링, 할당, 최적화하는 도구 모음. 예산 설정, 비용 분석, 알림 기능 제공.",
    detail: "Cost Management는 예산(Budget)을 설정해 초과 시 알림을 받거나, 비용 분석(Cost analysis)으로 서비스별/태그별 지출을 시각화하고, 비용 추천(Advisor 연동)으로 절감 기회를 찾아줍니다.",
    tip: "'비용 초과 알림', '예산 설정'이라는 표현이 나오면 Cost Management의 Budget 기능을 가리킵니다." },
  { topic: "cost-governance", front: "태그(Tags)를 사용하는 이유는?", back: "리소스에 메타데이터(이름-값 쌍)를 부여해 비용 추적, 리소스 구성/관리를 논리적으로 그룹화하기 위함.",
    detail: "태그는 이름-값 쌍(예: Environment=Production, CostCenter=Marketing)으로 리소스에 부여하며, 여러 리소스 그룹/구독에 걸쳐 있는 리소스를 부서·프로젝트·환경별로 비용 보고서에서 필터링/그룹화할 때 유용합니다.",
    tip: "태그는 리소스 관리(청구서 분류, 자동화 스크립트 대상 지정)에 쓰이지만 '보안 권한'과는 무관하다는 점(권한은 RBAC)에 유의하세요." },
  { topic: "cost-governance", front: "Azure Policy란?", back: "조직의 표준/규정 준수를 위해 리소스에 대한 규칙(정책)을 만들고 평가해 비준수 리소스를 감사하거나 방지하는 서비스.",
    detail: "Azure Policy는 '거부(Deny)', '감사(Audit)', '수정(Modify)' 같은 효과(effect)를 정의할 수 있으며, 예를 들어 '특정 리전에만 리소스 생성 허용' 같은 규칙을 강제할 수 있습니다. 여러 정책을 묶은 것을 이니셔티브(Initiative)라고 합니다.",
    tip: "Azure Policy는 '규정 준수를 강제/감사'하는 도구이고, RBAC는 '누가 무엇을 할 수 있는지'를 정하는 도구라는 차이를 구분하세요." },
  { topic: "cost-governance", front: "리소스 잠금(Resource Lock)이란?", back: "구독, 리소스 그룹, 리소스에 대해 실수로 삭제하거나 수정하는 것을 막는 잠금 기능(CanNotDelete, ReadOnly).",
    detail: "잠금은 상위 범위(구독, 리소스 그룹)에 설정하면 하위의 모든 리소스에 상속되며, Owner 권한이 있어도 잠금 자체를 먼저 제거하지 않으면 삭제나 수정이 불가능합니다.",
    tip: "CanNotDelete는 '삭제만' 막고 수정은 가능하며, ReadOnly는 '수정과 삭제 모두' 막는다는 차이를 정확히 구분해서 외우세요." },
  { topic: "cost-governance", front: "Azure Blueprints란?", back: "리소스 그룹, 정책, 역할 할당, ARM 템플릿 등을 하나의 패키지로 정의해 반복 가능하게 환경을 구성/배포하는 서비스.",
    detail: "Blueprints는 아티팩트(정책, 역할 할당, 리소스 그룹, ARM 템플릿)를 하나의 청사진으로 정의해 여러 구독에 일관되게 배포할 수 있게 하며, 배포 후에도 청사진과 환경 간의 연결(추적 관계)이 유지됩니다.",
    tip: "ARM 템플릿은 리소스 배포에만 집중하지만, Blueprints는 정책·역할까지 포함한 '환경 전체'를 패키징한다는 차이를 기억하세요." },
  { topic: "cost-governance", front: "Cloud Adoption Framework(CAF)란?", back: "조직이 클라우드 도입 전략을 수립하고 실행하기 위한 Microsoft의 모범 사례, 문서, 도구 모음.",
    detail: "CAF는 전략 수립(Strategy), 계획(Plan), 준비(Ready), 도입(Adopt), 거버넌스(Govern), 관리(Manage) 등의 단계로 구성된 방법론으로, 조직이 클라우드 도입 시 일관된 의사결정을 내리도록 돕습니다.",
    tip: "CAF는 특정 도구가 아니라 '모범 사례 모음/방법론'이라는 점을 기억하세요 — 시험에서 '프레임워크/가이드'로 표현됩니다." },

  // --- 모니터링·관리도구 ---
  { topic: "monitoring-tools", front: "Azure Monitor란?", back: "Azure 및 온프레미스 환경의 애플리케이션/인프라에서 텔레메트리 데이터를 수집, 분석, 대응하는 종합 모니터링 서비스.",
    detail: "Azure Monitor는 메트릭(숫자 성능 데이터)과 로그(이벤트 기반 데이터)라는 두 가지 데이터를 수집하며, 경고(Alert) 규칙을 만들어 임계치 초과 시 이메일/SMS/자동화 작업을 트리거할 수 있습니다.",
    tip: "'경고(Alert)를 설정해 임계치 초과 시 알림'이라는 표현은 Azure Monitor를 가리킵니다." },
  { topic: "monitoring-tools", front: "Azure Advisor의 역할은?", back: "비용, 보안, 안정성, 성능, 운영 우수성 관점에서 리소스 구성을 분석해 개인화된 모범 사례 권장사항을 제공.",
    detail: "Advisor는 실제 사용 데이터와 구성을 분석해 5가지 범주(비용, 보안, 안정성, 성능, 운영 우수성)로 나누어 추천을 제공하며, 추천을 적용하면 예상 절감액/개선 효과도 함께 보여줍니다.",
    tip: "'개인화된 권장사항(personalized recommendations)'이라는 표현은 Advisor를 가리킵니다." },
  { topic: "monitoring-tools", front: "Azure Service Health란?", back: "현재 진행 중인 Azure 서비스 문제, 계획된 유지 관리, 자신의 구독에 영향을 주는 상태를 알려주는 개인화된 대시보드.",
    detail: "Service Health는 Azure 전체의 상태를 보여주는 공개 Azure Status 페이지와 달리, 로그인한 구독에 실제로 영향을 주는 이벤트만 필터링해서 보여주는 개인화된 서비스입니다. 향후 유지 관리 일정도 미리 안내합니다.",
    tip: "'내 구독에 영향을 미치는 이벤트만'이라는 표현이 나오면 (전체 공개 상태 페이지가 아니라) Service Health가 정답입니다." },
  { topic: "monitoring-tools", front: "Azure Portal, CLI, PowerShell, Cloud Shell의 차이는?", back: "Portal: 웹 기반 GUI 관리. CLI/PowerShell: 명령줄 스크립트 기반 관리(자동화 용이). Cloud Shell: 브라우저에서 바로 쓰는 관리형 셸(CLI/PowerShell 모두 지원).",
    detail: "Azure CLI는 여러 OS(Windows/Linux/macOS)에서 동일하게 동작하는 명령줄 도구이고, PowerShell은 Windows 관리자에게 익숙한 cmdlet 방식입니다. Cloud Shell은 브라우저에서 별도 설치 없이 둘 다 사용할 수 있는 임시 관리 환경을 제공합니다.",
    tip: "'반복 가능한 자동화 스크립트'라는 표현이 나오면 Portal이 아니라 CLI/PowerShell/ARM 템플릿을 정답으로 고려하세요." },
  { topic: "monitoring-tools", front: "Log Analytics란?", back: "Azure Monitor의 일부로, 로그 데이터를 쿼리(KQL)해 분석할 수 있는 도구.",
    detail: "Log Analytics는 KQL(Kusto Query Language)로 방대한 로그 데이터를 검색·분석하며, 여러 리소스의 로그를 하나의 작업 영역(Workspace)에 모아 통합 분석할 수 있게 해줍니다.",
    tip: "'쿼리 언어로 로그를 분석한다'는 표현이 나오면 Log Analytics(및 KQL)를 가리킵니다." },
];

const QUIZ = [
  // --- 클라우드 개념 ---
  { topic: "cloud-concepts", q: "수요 변화에 따라 리소스가 자동으로 늘어나고 줄어드는 클라우드 특성은?", options: ["탄력성(Elasticity)", "민첩성(Agility)", "고가용성(High availability)", "내결함성(Fault tolerance)"], answer: 0, explain: "탄력성은 부하에 맞춰 리소스를 자동으로 조정하는 능력입니다. 확장성은 수동/자동 모두 포함하는 더 넓은 개념입니다.",
    detail: "확장성은 사람이 수동으로 VM 크기를 늘리는 것도 포함하는 더 넓은 개념이고, 탄력성은 그중에서도 '자동 조정'에 초점을 맞춘 하위 개념입니다.",
    tip: "'자동으로'라는 단어를 놓치지 마세요 — 이 단어가 있으면 대부분 탄력성이 정답입니다." },
  { topic: "cloud-concepts", q: "초기 대규모 자산 투자 대신 사용한 만큼 지불하는 방식으로 전환하는 것은?", options: ["OpEx로 전환", "CapEx로 전환", "TCO 증가", "SLA 강화"], answer: 0, explain: "클라우드는 자본 지출(CapEx)을 운영 지출(OpEx)로 전환시켜 초기 투자 부담을 줄입니다.",
    detail: "클라우드 이전은 서버를 사는 대신 사용한 만큼 매달 요금을 내는 구조로 바뀌므로 재무적으로 OpEx 모델에 해당합니다.",
    tip: "'선불 구매' 관련 단어가 보이면 오답(CapEx), '사용량 기반 청구'가 보이면 정답(OpEx)입니다." },
  { topic: "cloud-concepts", q: "다음 중 SaaS(Software as a Service)의 예시는?", options: ["Microsoft 365", "Azure Virtual Machines", "Azure App Service", "Azure Kubernetes Service"], answer: 0, explain: "Microsoft 365는 완성된 소프트웨어를 그대로 사용하는 SaaS입니다.",
    detail: "Azure Virtual Machines는 IaaS, Azure App Service는 PaaS, Azure Kubernetes Service는 컨테이너 오케스트레이션을 관리형으로 제공하는 서비스이며, 이 중 완성된 소프트웨어를 그대로 쓰는 것은 Microsoft 365뿐입니다.",
    tip: "보기에 Azure 관리형 서비스 이름이 여러 개 나오면, '내가 코드/설정을 전혀 건드리지 않고 바로 쓰는 것'을 찾으면 SaaS입니다." },
  { topic: "cloud-concepts", q: "공유 책임 모델에서 고객의 책임이 가장 큰 서비스 모델은?", options: ["IaaS", "PaaS", "SaaS", "모두 동일"], answer: 0, explain: "IaaS는 OS, 미들웨어, 데이터, 앱까지 고객이 관리해야 할 범위가 가장 넓습니다.",
    detail: "IaaS에서는 OS 패치, 네트워크 구성, 미들웨어, 데이터, 애플리케이션까지 고객이 관리해야 하지만, SaaS로 갈수록 이 책임이 Microsoft에게 넘어갑니다.",
    tip: "'책임이 가장 크다/작다'를 묻는 문제는 IaaS-PaaS-SaaS 스펙트럼을 떠올리면 바로 풀립니다." },
  { topic: "cloud-concepts", q: "단일 조직 전용으로 구축된 클라우드 인프라를 무엇이라 하는가?", options: ["프라이빗 클라우드", "퍼블릭 클라우드", "하이브리드 클라우드", "멀티 클라우드"], answer: 0, explain: "프라이빗 클라우드는 특정 조직만을 위한 전용 인프라입니다.",
    detail: "프라이빗 클라우드는 자체 데이터센터에 직접 구축하거나 특정 조직 전용으로 호스팅되는 인프라를 의미하며, 규정 준수나 보안이 매우 중요한 조직에서 선호됩니다.",
    tip: "'단일 조직 전용'이라는 표현이 프라이빗 클라우드를 가리키는 핵심 키워드입니다." },

  // --- Azure 아키텍처 ---
  { topic: "architecture", q: "리전 내에서 독립된 전원과 네트워크를 갖춘 물리적으로 분리된 데이터센터 그룹은?", options: ["가용성 영역(Availability Zone)", "가용성 집합(Availability Set)", "리전 페어(Region Pair)", "관리 그룹(Management Group)"], answer: 0, explain: "가용성 영역은 리전 내에서 물리적으로 분리된 데이터센터 그룹으로 최소 3개로 구성됩니다.",
    detail: "가용성 영역은 최소 3개 이상 존재해 여러 영역에 워크로드를 분산하면 한 영역 전체 장애에도 서비스를 유지할 수 있습니다.",
    tip: "'물리적으로 분리된 데이터센터 그룹'이라는 표현은 가용성 집합이 아니라 가용성 영역을 가리킵니다." },
  { topic: "architecture", q: "Azure 리소스 계층 구조에서 가장 상위 레벨은?", options: ["관리 그룹(Management Group)", "구독(Subscription)", "리소스 그룹(Resource Group)", "리소스(Resource)"], answer: 0, explain: "관리 그룹 → 구독 → 리소스 그룹 → 리소스 순서입니다.",
    detail: "관리 그룹을 사용하면 여러 구독에 정책과 권한을 한 번에 적용할 수 있어 대규모 조직의 거버넌스에 유용합니다.",
    tip: "계층 순서를 '관구리리(관리그룹-구독-리소스그룹-리소스)'처럼 나만의 방식으로 암기해두면 편리합니다." },
  { topic: "architecture", q: "리소스 그룹을 삭제하면 어떤 일이 발생하는가?", options: ["그룹 내 모든 리소스가 함께 삭제된다", "구독이 삭제된다", "리소스만 남고 그룹만 삭제된다", "아무 일도 일어나지 않는다"], answer: 0, explain: "리소스 그룹 삭제 시 그 안의 모든 리소스가 함께 삭제되므로 주의가 필요합니다.",
    detail: "리소스 그룹은 그 안의 리소스들의 수명 주기를 함께 관리하는 컨테이너이므로, 그룹을 삭제하면 되돌릴 수 없이 모든 리소스가 함께 사라집니다.",
    tip: "실수로 인한 전체 삭제를 막으려면 리소스 그룹에 Resource Lock(잠금)을 걸어두는 것이 좋습니다." },
  { topic: "architecture", q: "같은 지리 영역 내 최소 300마일 떨어진 두 리전을 짝지은 것은?", options: ["리전 페어(Region Pair)", "가용성 영역", "가용성 집합", "관리 그룹"], answer: 0, explain: "리전 페어는 재해 복구를 위해 서로 떨어진 두 리전을 짝짓는 개념입니다.",
    detail: "리전 페어는 Azure의 대규모 업데이트를 순차적으로 배포해 두 리전이 동시에 영향을 받지 않도록 설계되어 있습니다.",
    tip: "'300마일', '같은 지리적 영역'이라는 숫자/표현이 나오면 리전 페어입니다." },
  { topic: "architecture", q: "Azure Portal, CLI, PowerShell 요청이 공통적으로 거치는 배포/관리 계층은?", options: ["Azure Resource Manager(ARM)", "Azure Monitor", "Azure Policy", "Azure Advisor"], answer: 0, explain: "ARM은 모든 Azure 리소스 관리 요청을 처리하는 공통 계층입니다.",
    detail: "ARM은 모든 관리 요청(Portal, CLI, PowerShell, REST API)에 대해 동일한 인증/인가/로깅을 적용하는 단일 진입점 역할을 합니다.",
    tip: "'모든 도구가 공통으로 거치는 계층'이라는 표현은 항상 ARM을 가리킵니다." },

  // --- 컴퓨팅 서비스 ---
  { topic: "compute", q: "VM 프로비저닝 없이 컨테이너를 가장 빠르게 실행할 수 있는 서비스는?", options: ["Azure Container Instances", "Azure Kubernetes Service", "Azure Virtual Machines", "Azure Virtual Desktop"], answer: 0, explain: "ACI는 오케스트레이션 없이 컨테이너를 즉시 실행하는 서버리스 컨테이너 서비스입니다.",
    detail: "ACI는 VM을 미리 프로비저닝할 필요 없이 컨테이너 이미지를 지정하면 바로 실행되므로 짧은 배치 작업이나 테스트에 적합합니다.",
    tip: "'가장 빠르게', '오케스트레이션 불필요'는 AKS가 아니라 ACI를 가리키는 키워드입니다." },
  { topic: "compute", q: "코드 없이(Low-code) 워크플로우를 시각적으로 설계해 여러 서비스를 연결하는 서비스는?", options: ["Logic Apps", "Azure Functions", "Azure Kubernetes Service", "App Service"], answer: 0, explain: "Logic Apps는 로우코드 방식으로 워크플로우를 자동화합니다.",
    detail: "Logic Apps는 수백 개의 커넥터(Office 365, Salesforce, Twitter 등)를 제공해 코드를 작성하지 않고도 서비스 간 워크플로우를 연결할 수 있습니다.",
    tip: "'로우코드/노코드', '워크플로우 디자이너'라는 단어는 Logic Apps를 가리킵니다." },
  { topic: "compute", q: "관리형 Kubernetes 클러스터를 제공하는 서비스는?", options: ["Azure Kubernetes Service(AKS)", "Azure Container Instances(ACI)", "Azure App Service", "Azure Functions"], answer: 0, explain: "AKS는 Kubernetes 클러스터의 배포와 운영을 관리형으로 제공합니다.",
    detail: "AKS는 Kubernetes의 복잡한 클러스터 설치·업그레이드·모니터링 작업을 관리형으로 대신 처리해주어 컨테이너 오케스트레이션에 집중할 수 있게 합니다.",
    tip: "'관리형 Kubernetes'라는 표현이 나오면 무조건 AKS입니다." },
  { topic: "compute", q: "사용한 실행 시간만큼만 과금되는 이벤트 기반 서버리스 컴퓨트 서비스는?", options: ["Azure Functions", "Azure Virtual Machines", "VM Scale Sets", "Azure Virtual Desktop"], answer: 0, explain: "Azure Functions의 Consumption plan은 실행된 만큼만 과금됩니다.",
    detail: "Consumption plan은 함수가 실행되는 동안에만 리소스를 할당하고 유휴 시에는 완전히 스케일 다운되므로 비용 효율이 매우 높습니다.",
    tip: "'실행 시간만큼만 과금'이라는 표현은 서버리스(Functions)의 대표적 특징입니다." },
  { topic: "compute", q: "동일하게 구성된 VM 집합을 만들어 자동 확장/축소를 지원하는 서비스는?", options: ["VM Scale Sets", "Azure Container Instances", "Azure Functions", "App Service"], answer: 0, explain: "VM Scale Sets는 동일 구성 VM 그룹의 오토스케일을 지원합니다.",
    detail: "Scale Sets는 부하 분산 장치와 결합해 사용되며, 인스턴스 수를 늘리거나 줄이는 규칙(오토스케일 규칙)을 CPU/메모리/큐 길이 등 지표 기반으로 설정할 수 있습니다.",
    tip: "'동일 구성의 VM을 여러 대', '자동 확장/축소'라는 표현은 VM Scale Sets를 가리킵니다." },

  // --- 네트워킹 ---
  { topic: "networking", q: "공용 인터넷을 거치지 않고 온프레미스와 Azure를 전용 사설 연결로 연결하는 서비스는?", options: ["ExpressRoute", "VPN Gateway", "Azure DNS", "Traffic Manager"], answer: 0, explain: "ExpressRoute는 통신사를 통한 전용 회선으로 인터넷을 거치지 않습니다.",
    detail: "ExpressRoute는 연결 제공업체의 사설 네트워크를 통해 Azure와 직접 연결되므로 공용 인터넷의 혼잡이나 보안 위협의 영향을 받지 않습니다.",
    tip: "'전용 사설 연결', '공용 인터넷 미경유'라는 표현은 ExpressRoute를 가리킵니다." },
  { topic: "networking", q: "URL 경로 기반 라우팅 등 HTTP(S) 계층(7계층) 트래픽을 처리하는 서비스는?", options: ["Application Gateway", "Load Balancer", "VPN Gateway", "ExpressRoute"], answer: 0, explain: "Application Gateway는 애플리케이션 계층(L7)에서 동작하며 WAF도 포함할 수 있습니다.",
    detail: "Application Gateway는 HTTP 헤더, 쿠키, URL 경로 등 애플리케이션 계층 정보를 보고 라우팅 결정을 내릴 수 있어 마이크로서비스별로 트래픽을 나누는 데 유용합니다.",
    tip: "'7계층', 'URL 기반 라우팅', 'WAF'라는 단어는 Load Balancer가 아니라 Application Gateway를 가리킵니다." },
  { topic: "networking", q: "DNS 기반으로 여러 리전의 엔드포인트에 트래픽을 분산시키는 서비스는?", options: ["Traffic Manager", "Load Balancer", "Application Gateway", "Azure Firewall"], answer: 0, explain: "Traffic Manager는 DNS 레벨에서 전역 트래픽 라우팅을 수행합니다.",
    detail: "Traffic Manager는 실제 데이터 트래픽이 아니라 DNS 조회 단계에서만 개입하므로, 트래픽 자체를 중계하는 부하 분산 장치와는 동작 방식이 다릅니다.",
    tip: "'여러 리전', 'DNS 기반'이라는 표현이 함께 나오면 Traffic Manager입니다." },
  { topic: "networking", q: "Azure 리소스가 인터넷 및 온프레미스와 안전하게 통신하는 기본 네트워킹 구성 요소는?", options: ["가상 네트워크(VNet)", "Azure CDN", "Azure DNS", "Network Security Group"], answer: 0, explain: "VNet은 Azure 네트워킹의 기본 구성 요소입니다.",
    detail: "VNet은 Azure 네트워킹의 기초가 되는 리소스로, 서브넷, NSG, 라우팅 테이블 등 다른 네트워킹 구성 요소들이 모두 VNet을 기반으로 동작합니다.",
    tip: "'Azure 네트워킹의 기본 구성 요소'라는 표현은 항상 VNet(가상 네트워크)을 가리킵니다." },
  { topic: "networking", q: "정적 콘텐츠를 사용자와 지리적으로 가까운 서버에서 제공해 지연 시간을 줄이는 서비스는?", options: ["Azure CDN", "ExpressRoute", "VPN Gateway", "Load Balancer"], answer: 0, explain: "CDN은 전 세계에 분산된 캐시 서버를 통해 콘텐츠 전달 속도를 높입니다.",
    detail: "CDN은 캐시 서버(POP, Point of Presence)를 전 세계에 두어 콘텐츠 요청을 원본 서버까지 가지 않고도 처리할 수 있게 해 응답 속도를 크게 개선합니다.",
    tip: "'정적 콘텐츠', '지리적으로 가까운 서버'라는 표현은 CDN의 핵심 키워드입니다." },

  // --- 스토리지 ---
  { topic: "storage", q: "거의 접근하지 않는 데이터를 가장 저렴하게 저장하는 Blob 액세스 계층은?", options: ["Archive", "Hot", "Cool", "Premium"], answer: 0, explain: "Archive 계층은 오프라인 저장이며 최소 180일 보관, 가장 저렴하지만 접근 시 재수화(rehydrate)가 필요합니다.",
    detail: "Archive 계층은 오프라인 상태로 저장되어 스토리지 비용은 가장 저렴하지만, 데이터를 읽으려면 몇 시간이 걸릴 수 있는 재수화(rehydrate) 과정이 필요합니다.",
    tip: "'거의 접근 안 함 + 오프라인 + 최저 비용'이라는 조합은 Archive를 가리킵니다." },
  { topic: "storage", q: "주 리전과 페어 리전(다른 지리적 위치) 모두에 데이터를 복제하는 중복 옵션은?", options: ["GRS", "LRS", "ZRS", "없음"], answer: 0, explain: "GRS(Geo-redundant storage)는 주 리전과 페어 리전에 각각 복제본을 저장합니다.",
    detail: "GRS는 주 리전에 장애가 발생해도 페어 리전에 복제된 데이터로 복구할 수 있게 해주는 지역 중복 옵션으로, RA-GRS를 사용하면 평상시에도 보조 리전에서 읽기가 가능합니다.",
    tip: "'다른 지리적 위치(리전)에 복제'라는 표현이 나오면 LRS/ZRS가 아니라 GRS 이상을 가리킵니다." },
  { topic: "storage", q: "SMB/NFS 프로토콜로 클라우드와 온프레미스에서 동시에 마운트 가능한 완전관리형 파일 공유는?", options: ["Azure Files", "Azure Blob Storage", "Azure Disk Storage", "Azure Data Box"], answer: 0, explain: "Azure Files는 표준 파일 공유 프로토콜을 지원하는 관리형 서비스입니다.",
    detail: "Azure Files는 표준 SMB/NFS 클라이언트로 마운트할 수 있어 기존 파일 서버 애플리케이션을 코드 수정 없이 그대로 사용할 수 있다는 장점이 있습니다.",
    tip: "'여러 사용자/VM이 동시에 접근하는 공유 폴더'라는 표현은 Azure Files를 가리킵니다." },
  { topic: "storage", q: "대용량 오프라인 데이터를 물리적 장치로 Azure에 전송하는 서비스는?", options: ["Azure Data Box", "Azure Migrate", "Azure Files", "Azure Import/Export만 가능"], answer: 0, explain: "Azure Data Box는 네트워크 대역폭이 부족할 때 물리적 장치로 대용량 데이터를 옮깁니다.",
    detail: "Data Box는 네트워크로 전송하면 수 주가 걸릴 대용량 데이터(수십 TB 이상)를 물리적 장치에 담아 우편으로 보내는 방식으로 훨씬 빠르게 옮길 수 있습니다.",
    tip: "'물리적 장치', '대역폭 부족'이라는 키워드는 Data Box를 가리킵니다." },
  { topic: "storage", q: "Azure VM에 연결하는 블록 수준 스토리지는?", options: ["Azure Disk Storage", "Azure Blob Storage", "Azure Files", "Azure Table Storage"], answer: 0, explain: "Disk Storage는 VM의 가상 하드 디스크로 사용됩니다.",
    detail: "관리 디스크(Managed Disk)는 스토리지 계정 관리를 Azure가 대신 해주며, 성능 등급(Standard HDD/SSD, Premium SSD, Ultra Disk)에 따라 IOPS와 처리량이 달라집니다.",
    tip: "'VM에 연결되는 디스크'라는 표현은 Blob이 아니라 Disk Storage를 가리킵니다." },

  // --- ID/보안 ---
  { topic: "identity-security", q: "인증된 사용자가 무엇에 접근할 수 있는지 결정하는 과정은?", options: ["인가(Authorization)", "인증(Authentication)", "감사(Auditing)", "암호화(Encryption)"], answer: 0, explain: "인증은 신원 확인, 인가는 권한 결정입니다.",
    detail: "인가 단계는 인증이 성공적으로 끝난 뒤에만 진행되며, RBAC 같은 메커니즘을 통해 실제 접근 가능한 범위를 결정합니다.",
    tip: "'무엇을 할 수 있는지 결정'이라는 표현은 인증이 아니라 인가(Authorization)를 가리킵니다." },
  { topic: "identity-security", q: "위치, 기기 상태 등의 신호를 바탕으로 액세스 정책을 자동 적용하는 기능은?", options: ["조건부 액세스(Conditional Access)", "MFA", "RBAC", "Azure Policy"], answer: 0, explain: "조건부 액세스는 신호 기반으로 액세스 여부를 동적으로 결정합니다.",
    detail: "조건부 액세스는 로그인 시점의 위치, 기기 상태, 위험도 등 다양한 신호를 실시간으로 평가해 접근 허용/차단/추가 인증 요구를 자동으로 결정합니다.",
    tip: "'신호(signal) 기반 자동 정책'이라는 표현은 조건부 액세스를 가리키는 핵심 키워드입니다." },
  { topic: "identity-security", q: "사용자/그룹에 리소스에 대한 역할을 할당해 세분화된 권한을 관리하는 시스템은?", options: ["RBAC", "MFA", "Conditional Access", "Zero Trust"], answer: 0, explain: "RBAC(역할 기반 액세스 제어)는 Reader, Contributor, Owner 등의 역할을 할당합니다.",
    detail: "RBAC는 역할 정의(무엇을 할 수 있는지)와 역할 할당(누구에게, 어느 범위에)이라는 두 요소로 구성되며, 최소 권한 원칙에 따라 필요한 역할만 부여하는 것이 모범 사례입니다.",
    tip: "'세분화된 권한 관리'라는 표현은 RBAC를 가리킵니다." },
  { topic: "identity-security", q: "제로 트러스트 원칙에 해당하지 않는 것은?", options: ["암묵적 신뢰(Implicit trust) 부여", "명시적 검증(Verify explicitly)", "최소 권한 액세스", "침해 가정(Assume breach)"], answer: 0, explain: "제로 트러스트는 암묵적 신뢰를 배제하고 항상 명시적으로 검증하는 것이 핵심입니다.",
    detail: "'암묵적 신뢰'는 제로 트러스트가 정확히 배격하는 개념으로, 사내망에 있다는 이유만으로 신뢰하지 않고 모든 요청을 매번 검증합니다.",
    tip: "제로 트러스트의 3원칙(명시적 검증/최소 권한/침해 가정)을 벗어나는 보기를 찾는 문제가 자주 출제됩니다." },
  { topic: "identity-security", q: "클라우드 기반 SIEM + SOAR 솔루션은?", options: ["Microsoft Sentinel", "Microsoft Defender for Cloud", "Microsoft Entra ID", "Azure Policy"], answer: 0, explain: "Sentinel은 보안 이벤트 수집/분석(SIEM)과 자동 대응(SOAR)을 함께 제공합니다.",
    detail: "Sentinel은 SIEM 기능(로그 수집·상관 분석)과 SOAR 기능(자동화된 대응)을 하나의 클라우드 서비스로 통합해 제공합니다.",
    tip: "'SIEM + SOAR'라는 조합 키워드가 나오면 항상 Microsoft Sentinel이 정답입니다." },

  // --- 비용 관리·거버넌스 ---
  { topic: "cost-governance", q: "온프레미스 대비 Azure 이전 시 비용 절감을 비교하는 도구는?", options: ["TCO Calculator", "Pricing Calculator", "Azure Cost Management", "Azure Advisor"], answer: 0, explain: "TCO Calculator는 총소유비용 비교를 위한 도구입니다.",
    detail: "TCO Calculator는 현재 온프레미스 인프라(서버, 스토리지, 인건비, 전력 등)를 입력받아 Azure로 이전했을 때의 총소유비용 차이를 추정해줍니다.",
    tip: "'온프레미스 대비 절감액 비교'라는 표현은 Pricing Calculator가 아니라 TCO Calculator를 가리킵니다." },
  { topic: "cost-governance", q: "구독/리소스 그룹/리소스가 실수로 삭제되거나 수정되는 것을 막는 기능은?", options: ["리소스 잠금(Resource Lock)", "Azure Policy", "RBAC", "태그(Tags)"], answer: 0, explain: "리소스 잠금은 CanNotDelete, ReadOnly 두 가지 유형이 있습니다.",
    detail: "리소스 잠금은 RBAC 권한과 별개로 동작하므로, Owner 권한이 있어도 잠금이 걸려 있으면 잠금을 먼저 해제해야 삭제/수정이 가능합니다.",
    tip: "'실수 방지'라는 표현이 나오면 Azure Policy가 아니라 Resource Lock을 먼저 고려하세요." },
  { topic: "cost-governance", q: "리소스 그룹, 정책, 역할 할당 등을 패키지로 묶어 반복 가능하게 환경을 구성하는 서비스는?", options: ["Azure Blueprints", "Azure Policy", "ARM 템플릿만 가능", "Resource Lock"], answer: 0, explain: "Blueprints는 여러 구성 요소를 하나의 패키지로 정의해 재사용합니다.",
    detail: "Blueprints는 정책, 역할 할당, 리소스 그룹, ARM 템플릿을 하나로 묶어 배포하므로, 신규 구독에 조직 표준 환경을 빠르게 복제할 때 유용합니다.",
    tip: "'패키지로 묶어 반복 배포'라는 표현은 ARM 템플릿 단독이 아니라 Blueprints를 가리킵니다." },
  { topic: "cost-governance", q: "조직의 규정 준수를 위해 리소스에 규칙을 적용하고 비준수를 감사/방지하는 서비스는?", options: ["Azure Policy", "Azure Blueprints", "RBAC", "Cost Management"], answer: 0, explain: "Azure Policy는 조직 표준 준수를 위한 규칙 평가 서비스입니다.",
    detail: "Azure Policy는 새 리소스가 생성될 때 규칙을 위반하면 생성을 막거나(Deny), 이미 있는 리소스는 비준수로 표시(Audit)하는 식으로 동작합니다.",
    tip: "'규정 준수 강제/감사'라는 표현은 RBAC가 아니라 Azure Policy를 가리킵니다." },
  { topic: "cost-governance", q: "리소스에 이름-값 쌍의 메타데이터를 붙여 비용 추적/그룹화하는 기능은?", options: ["태그(Tags)", "Resource Lock", "Management Group", "Blueprints"], answer: 0, explain: "태그는 리소스를 논리적으로 분류하고 비용 보고서에서 필터링하는 데 사용됩니다.",
    detail: "태그는 부서, 프로젝트, 환경(dev/test/prod) 등 조직에 맞는 분류 기준으로 자유롭게 정의할 수 있으며, 비용 분석 보고서에서 태그별로 필터링할 수 있습니다.",
    tip: "'비용을 부서/프로젝트별로 나눠서 본다'는 표현은 태그(Tags)를 가리킵니다." },

  // --- 모니터링·관리도구 ---
  { topic: "monitoring-tools", q: "비용, 보안, 안정성, 성능 관점에서 개인화된 모범 사례를 권장하는 서비스는?", options: ["Azure Advisor", "Azure Monitor", "Azure Policy", "Service Health"], answer: 0, explain: "Advisor는 구성 분석 후 맞춤형 권장사항을 제시합니다.",
    detail: "Advisor는 실제 리소스 사용 패턴을 분석해 'VM 크기를 줄이세요', 'MFA를 활성화하세요'와 같은 구체적인 실행 항목을 제안합니다.",
    tip: "'개인화된 모범 사례'라는 표현은 Azure Monitor가 아니라 Advisor를 가리킵니다." },
  { topic: "monitoring-tools", q: "진행 중인 서비스 문제나 계획된 유지 관리로 인한 영향을 알려주는 개인화된 대시보드는?", options: ["Azure Service Health", "Azure Monitor", "Azure Advisor", "Log Analytics"], answer: 0, explain: "Service Health는 구독에 영향을 주는 이벤트를 개인화해서 보여줍니다.",
    detail: "Service Health는 Azure 전체 상태를 보여주는 공개 Status 페이지와 달리 내 구독에 실제로 영향을 주는 이벤트만 필터링해서 알려주는 개인화된 서비스입니다.",
    tip: "'내 구독에 영향을 주는'이라는 표현이 핵심 — Service Health와 Azure Status 페이지를 구분하는 키워드입니다." },
  { topic: "monitoring-tools", q: "로그 데이터를 KQL로 쿼리해 분석하는 Azure Monitor의 구성 요소는?", options: ["Log Analytics", "Azure Advisor", "Azure Policy", "Resource Lock"], answer: 0, explain: "Log Analytics는 Azure Monitor 내에서 로그 쿼리 및 분석을 담당합니다.",
    detail: "Log Analytics 작업 영역(Workspace)에는 여러 리소스의 로그를 한 곳에 모을 수 있어 여러 서비스를 넘나드는 문제를 KQL 쿼리 하나로 분석할 수 있습니다.",
    tip: "'쿼리 언어(KQL)로 로그 분석'이라는 표현은 Log Analytics를 가리킵니다." },
  { topic: "monitoring-tools", q: "브라우저에서 바로 사용할 수 있는 관리형 셸로 CLI/PowerShell을 모두 지원하는 것은?", options: ["Azure Cloud Shell", "Azure Portal", "Azure Advisor", "ARM 템플릿"], answer: 0, explain: "Cloud Shell은 설치 없이 브라우저에서 바로 명령줄 관리를 할 수 있게 합니다.",
    detail: "Cloud Shell은 매번 새 세션에서 임시 컨테이너를 실행하며, 파일을 유지하려면 연결된 Azure Files 공유에 저장해야 합니다.",
    tip: "'브라우저에서 설치 없이 바로'라는 표현은 Cloud Shell을 가리킵니다." },
  { topic: "monitoring-tools", q: "Azure 및 온프레미스 텔레메트리 데이터를 수집·분석·대응하는 종합 모니터링 서비스는?", options: ["Azure Monitor", "Azure Advisor", "Azure Policy", "Azure Blueprints"], answer: 0, explain: "Azure Monitor는 메트릭, 로그 등 다양한 텔레메트리를 통합 수집/분석합니다.",
    detail: "Azure Monitor는 Log Analytics, Application Insights, 경고(Alerts), 대시보드 등 여러 하위 기능을 포괄하는 상위 개념의 모니터링 플랫폼입니다.",
    tip: "Log Analytics는 Azure Monitor의 '일부 기능'이라는 포함 관계를 기억하세요." },
];

const PLAN_DAYS = [
  { day: 1, domain: 1, title: "클라우드 개념 기초", items: [
    "클라우드 이점: HA/확장성/탄력성/민첩성/DR",
    "비용 모델: CapEx vs OpEx, 종량제",
    "클라우드 vs 온프레미스 비교표 작성",
    "Microsoft Learn '클라우드 컴퓨팅 개념' 완료",
    "플래시카드 '클라우드 개념' 1회 학습",
  ]},
  { day: 2, domain: 1, title: "서비스/배포 모델", items: [
    "IaaS/PaaS/SaaS 정의 및 책임 분담 비교",
    "공유 책임 모델 이해",
    "배포 모델: 퍼블릭/프라이빗/하이브리드/멀티클라우드",
    "서비스 모델별 Azure 서비스 예시 정리",
    "퀴즈 '클라우드 개념' 세트 풀이 (목표 80%+)",
  ]},
  { day: 3, domain: 2, title: "Azure 핵심 아키텍처", items: [
    "리전/리전 페어/소버린 리전 개념",
    "가용성 영역 vs 가용성 집합 차이",
    "관리 그룹→구독→리소스 그룹→리소스 계층 구조",
    "ARM의 역할과 템플릿 개념",
    "플래시카드 'Azure 아키텍처' 1회 학습",
  ]},
  { day: 4, domain: 2, title: "컴퓨팅 서비스", items: [
    "VM, VM Scale Sets",
    "App Service, ACI, AKS",
    "Azure Functions vs Logic Apps",
    "Azure Virtual Desktop 개요",
    "퀴즈 '컴퓨팅 서비스' 세트 풀이",
  ]},
  { day: 5, domain: 2, title: "네트워킹 서비스", items: [
    "VNet, 서브넷 개념",
    "VPN Gateway vs ExpressRoute",
    "Azure DNS, Load Balancer vs App Gateway vs Traffic Manager",
    "Azure CDN, Front Door 개요",
    "플래시카드 '네트워킹' 1회 학습",
  ]},
  { day: 6, domain: 2, title: "스토리지 서비스", items: [
    "Blob/Disk/File/Queue/Table 차이",
    "Blob 액세스 계층: Hot/Cool/Archive",
    "중복 옵션: LRS/ZRS/GRS/GZRS",
    "데이터 이전 도구: Migrate/Data Box/File Sync",
    "퀴즈 '스토리지' 세트 풀이",
  ]},
  { day: 7, domain: 'mixed', title: "복습 + 모의고사 1", items: [
    "Day 1~6 플래시카드 재학습(오답 위주)",
    "종합 모의고사 1 (도메인 1~2, 목표 80%+)",
    "오답 노트 정리",
    "취약 주제 재학습",
  ]},
  { day: 8, domain: 3, title: "ID/액세스/보안", items: [
    "Entra ID: 인증 vs 인가",
    "MFA, 조건부 액세스, SSO",
    "RBAC 개념과 범위",
    "제로 트러스트, 심층 방어",
    "Defender for Cloud, Sentinel 개요",
    "플래시카드 'ID/보안' 1회 학습",
  ]},
  { day: 9, domain: 3, title: "비용 관리 및 거버넌스", items: [
    "Pricing Calculator vs TCO Calculator",
    "Cost Management, 예산, 태그",
    "Azure Policy, Resource Locks, Blueprints",
    "Cloud Adoption Framework 개요",
    "퀴즈 '비용 관리·거버넌스' 세트 풀이",
  ]},
  { day: 10, domain: 3, title: "모니터링/관리도구 + 최종 모의고사", items: [
    "Azure Monitor, Log Analytics, Advisor, Service Health",
    "Portal vs CLI vs PowerShell vs Cloud Shell",
    "종합 모의고사 2 (전 도메인, 목표 85%+)",
    "전체 오답 노트 최종 복습",
    "시험 응시 환경/절차 확인",
  ]},
];
